### PR TITLE
Add SC&TC README file.

### PR DESCRIPTION
**Pull request by yorushika**
Done!

### CODE REVIEW

**Comment by bsides** [comment]
Thanks @yorushika! I did some changes in the README recently. They aren't much but do you mind doing them too? Those 5 ones I did on April 7 https://github.com/bsides/horizoverlay/commits/master/README.md

**Comment by yorushika** [comment]
All translation is done. Also found and fixed somewhere I missed in the first edition translation of README, that's so shame. Forgive me QVQ

开 2018/4/10 2:30:51, Rafael Pereira <notifications@github.com> 写到:

Thanks @yorushika<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyorushika&data=02%7C01%7C%7Cf533c04cee574a8ed7c508d59e480378%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636588954492239124&sdata=YA3nH0r%2F8YeqXt0z9fPoKhU5RUEOFmOEQEJQgQRvLcc%3D&reserved=0>! I did some changes in the README recently. They aren't much but do you mind doing them too? Those 5 ones I did on April 7 https://github.com/bsides/horizoverlay/commits/master/README.md<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbsides%2Fhorizoverlay%2Fcommits%2Fmaster%2FREADME.md&data=02%7C01%7C%7Cf533c04cee574a8ed7c508d59e480378%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636588954492239124&sdata=G%2BC3SwvTa0Zoj2FMPV4RN%2Fi9VhKbAV%2BuBNV8ZtaUeus%3D&reserved=0>

**Comment by bsides** [comment]
@yorushika I believe all translations were done in the previous PR, could you please check if everything is fine? Thank you!

**Comment by yorushika** [comment]
Sure!

    -- Yorushika

开 2018/5/7 8:59:52, Rafael Pereira <notifications@github.com> 写到:

@yorushika<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyorushika&data=02%7C01%7C%7C4efd2021e0b34f0782c608d5b3b5d592%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636612515916287165&sdata=enbLdg5zxwNsJkDXu3LS8%2FTlf9JqJumeFk9IpNzQsUo%3D&reserved=0> I believe all translations were done in the previous PR, could you please check if everything is fine? Thank you!

**Pull request closed without merging**
